services:
  - type: web
    name: wechaty-puppet-service
    env: node
    plan: free
    region: singapore

    # 先生成 package.json 并在构建阶段把依赖装好，减少启动时长
    buildCommand: |
      npm init -y
      npm install wechaty-puppet-service@latest --omit=dev --no-audit --no-fund

    # 启动时不再安装，直接用本地 bin，并且显式指定 host/port
    startCommand: >
      sh -lc "
      export WECHATY_PUPPET_SERVER_PORT=$PORT;
      ./node_modules/.bin/wechaty-puppet-service start --host 0.0.0.0 --port $PORT
      "

    envVars:
      - key: WECHATY_PUPPET
        value: wechaty-puppet-wechat
      - key: WECHATY_TOKEN
        sync: false
      - key: WECHATY_LOG
        value: verbose
