services:
  - type: web
    name: wechaty-puppet-service
    env: node
    plan: free
    region: singapore
    buildCommand: "echo ok"
    startCommand: >
      sh -lc "export WECHATY_PUPPET_SERVER_PORT=$PORT;
      npm exec -y -p wechaty-puppet-service wechaty-puppet-service start"
    envVars:
      - key: WECHATY_PUPPET
        value: wechaty-puppet-wechat
      - key: WECHATY_TOKEN
        sync: false
      - key: WECHATY_LOG
        value: verbose
