services:
  - type: web
    name: wechaty-puppet-service
    env: node
    plan: free
    region: singapore
    buildCommand: npm install -g wechaty-puppet-service@latest
    startCommand: bash -lc "export WECHATY_PUPPET_SERVER_PORT=$PORT; wechaty-puppet-service start"
    envVars:
      - key: WECHATY_PUPPET
        value: wechaty-puppet-wechat
      - key: WECHATY_TOKEN
        sync: false
      - key: WECHATY_LOG
        value: verbose