services:
  - type: web
    name: wechaty-puppet-service
    env: node
    plan: free
    region: singapore

    # 1) 本地安装（非 -g）
buildCommand: "echo ok"   # 不需要提前安装，直接占位



    # 2) 用 npx 启动；确保监听 Render 注入的 $PORT
startCommand: >
  sh -lc "export WECHATY_PUPPET_SERVER_PORT=$PORT;
  npx -y -p wechaty-puppet-service wechaty-puppet-service start"


    envVars:
      - key: WECHATY_PUPPET
        value: wechaty-puppet-wechat
      - key: WECHATY_TOKEN
        sync: false
      - key: WECHATY_LOG
        value: verbose
