services:
  - type: web
    name: wechaty-puppet-service
    runtime: docker     # 使用仓库里的 Dockerfile 构建
    plan: free
    region: singapore
    envVars:
      - key: WECHATY_PUPPET
        value: wechaty-puppet-wechat
      - key: WECHATY_TOKEN
        sync: false
      - key: WECHATY_LOG
        value: verbose
